//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP_Tema_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentIntervention
    {
        public int IdAppointmentIntervention { get; set; }
        public int IdAppointment { get; set; }
        public int IdInterventie { get; set; }
        public string Deleted { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Intervention Intervention { get; set; }
    }
}
