//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP_Tema_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int IdPrice { get; set; }
        public int IdIntervention { get; set; }
        public System.DateTime StartingDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public int Value { get; set; }
        public string Deleted { get; set; }
    
        public virtual Intervention Intervention { get; set; }
    }
}
